//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNDave.Modules.IonicToDo.ViewModels
{
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// A viewmodel that exposes all resource keys in strong types.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class LocalizationViewModel
    {


    }
}
